module.exports = (MongoConnection) => ({
  User: MongoConnection.model("User", require("./user")),
  Profile: MongoConnection.model("Profile", require("./profile")),
  Comment: MongoConnection.model("Comment", require("./comment")),
  Tag: MongoConnection.model("Tag", require("./tag")),
  Track: MongoConnection.model("Track", require("./track")),
  Transaction: MongoConnection.model("Transaction", require("./transaction")),
  Contact: MongoConnection.model("Contact", require("./contact")),
  CustomLayer: MongoConnection.model("CustomLayer", require("./custom_layer")),
  SearchHistory: MongoConnection.model("SearchHistory", require("./searchHistory")),
  Message: MongoConnection.model("Message", require("./message")),
  File: MongoConnection.model("File", require("./file")),
  FileLayer: MongoConnection.model("FileLayer", require("./file_layer")),
  MelissaRecord: MongoConnection.model("MelissaRecord", require("./melissaRecord")),
  MelissaAddressRecord: MongoConnection.model("MelissaAddressRecord", require("./melissaAddressRecord")),
  MelissaRecordUpdate: MongoConnection.model("MelissaRecordUpdate", require("./melissaRecordUpdate")),
  LayerConfig: MongoConnection.model("LayerConfig", require("./ud_layer_config")),
  Entity: MongoConnection.model("Entity", require("./entity")),
  ParcelOwnership: MongoConnection.model("ParcelOwnership", require("./parcelOwnership")),
  LayersState: MongoConnection.model("LayersState", require("./layersState")),
});
